src/Entity/Offer.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OfferRepository")
 */
class Offer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Job", inversedBy="department")
     * @ORM\JoinColumn(nullable=false)
     */
    private $job;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Department", inversedBy="offers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $department;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contact_email;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Candidate", mappedBy="offer_candidate")
     */
    private $candidates;

    public function __construct()
    {
        $this->candidates = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getJob(): ?Job
    {
        return $this->job;
    }

    public function setJob(?Job $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(string $contact_email): self
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * @return Collection|Candidate[]
     */
    public function getCandidates(): Collection
    {
        return $this->candidates;
    }

    public function addCandidate(Candidate $candidate): self
    {
        if (!$this->candidates->contains($candidate)) {
            $this->candidates[] = $candidate;
            $candidate->setOfferCandidate($this);
        }

        return $this;
    }

    public function removeCandidate(Candidate $candidate): self
    {
        if ($this->candidates->contains($candidate)) {
            $this->candidates->removeElement($candidate);
            // set the owning side to null (unless already changed)
            if ($candidate->getOfferCandidate() === $this) {
                $candidate->setOfferCandidate(null);
            }
        }

        return $this;
    }
}

src/Form/OfferType.php
<?php

namespace App\Form;

use App\Entity\Offer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OfferType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('created_at')
            ->add('description')
            ->add('zipcode')
            ->add('city')
            ->add('contact_email')
            ->add('reference')
            ->add('latitude')
            ->add('longitude')
            ->add('job')
            ->add('department')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Offer::class,
        ]);
    }
}

src/Controller/OfferController.php
<?php

namespace App\Controller;

use App\Entity\Offer;
use App\Form\OfferType;
use App\Repository\OfferRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/offer")
 */
class OfferController extends AbstractController
{
    /**
     * @Route("/", name="offer_index", methods={"GET"})
     */
    public function index(OfferRepository $offerRepository): Response
    {
        return $this->render('offer/index.html.twig', [
            'offers' => $offerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="offer_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $offer = new Offer();
        $form = $this->createForm(OfferType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($offer);
            $entityManager->flush();

            return $this->redirectToRoute('offer_index');
        }

        return $this->render('offer/new.html.twig', [
            'offer' => $offer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="offer_show", methods={"GET"})
     */
    public function show(Offer $offer): Response
    {
        return $this->render('offer/show.html.twig', [
            'offer' => $offer,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="offer_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Offer $offer): Response
    {
        $form = $this->createForm(OfferType::class, $offer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('offer_index', [
                'id' => $offer->getId(),
            ]);
        }

        return $this->render('offer/edit.html.twig', [
            'offer' => $offer,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="offer_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Offer $offer): Response
    {
        if ($this->isCsrfTokenValid('delete'.$offer->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($offer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('offer_index');
    }
}

templates/offer/_delete_form.html.twig
<form method="post" action="{{ path('offer_delete', {'id': offer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ offer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/offer/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/offer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Offer{% endblock %}

{% block body %}
    <h1>Edit Offer</h1>

    {{ include('offer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('offer_index') }}">back to list</a>

    {{ include('offer/_delete_form.html.twig') }}
{% endblock %}

templates/offer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offer index{% endblock %}

{% block body %}
    <h1>Offer index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Created_at</th>
                <th>Description</th>
                <th>Zipcode</th>
                <th>City</th>
                <th>Contact_email</th>
                <th>Reference</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for offer in offers %}
            <tr>
                <td>{{ offer.id }}</td>
                <td>{{ offer.createdAt ? offer.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ offer.description }}</td>
                <td>{{ offer.zipcode }}</td>
                <td>{{ offer.city }}</td>
                <td>{{ offer.contactEmail }}</td>
                <td>{{ offer.reference }}</td>
                <td>{{ offer.latitude }}</td>
                <td>{{ offer.longitude }}</td>
                <td>
                    <a href="{{ path('offer_show', {'id': offer.id}) }}">show</a>
                    <a href="{{ path('offer_edit', {'id': offer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('offer_new') }}">Create new</a>
{% endblock %}

templates/offer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Offer{% endblock %}

{% block body %}
    <h1>Create new Offer</h1>

    {{ include('offer/_form.html.twig') }}

    <a href="{{ path('offer_index') }}">back to list</a>
{% endblock %}

templates/offer/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offer{% endblock %}

{% block body %}
    <h1>Offer</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ offer.id }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ offer.createdAt ? offer.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ offer.description }}</td>
            </tr>
            <tr>
                <th>Zipcode</th>
                <td>{{ offer.zipcode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ offer.city }}</td>
            </tr>
            <tr>
                <th>Contact_email</th>
                <td>{{ offer.contactEmail }}</td>
            </tr>
            <tr>
                <th>Reference</th>
                <td>{{ offer.reference }}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{ offer.latitude }}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{ offer.longitude }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('offer_index') }}">back to list</a>

    <a href="{{ path('offer_edit', {'id': offer.id}) }}">edit</a>

    {{ include('offer/_delete_form.html.twig') }}
{% endblock %}