src/Entity/Candidate.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CandidateRepository")
 */
class Candidate
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_candidature;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Offer", inversedBy="candidates")
     */
    private $offer_candidate;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateCandidature(): ?\DateTimeInterface
    {
        return $this->date_candidature;
    }

    public function setDateCandidature(\DateTimeInterface $date_candidature): self
    {
        $this->date_candidature = $date_candidature;

        return $this;
    }


    public function getOfferCandidate(): ?Offer
    {
        return $this->offer_candidate;
    }

    public function setOfferCandidate(?Offer $offer_candidate): self
    {
        $this->offer_candidate = $offer_candidate;

        return $this;
    }
}

src/Form/CandidateType.php
<?php

namespace App\Form;

use App\Entity\Candidate;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CandidateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('date_de_naissance')
            ->add('email')
            ->add('date_candidature')
            ->add('offer_candidate')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Candidate::class,
        ]);
    }
}

src/Controller/CandidateController.php
<?php

namespace App\Controller;

use App\Entity\Candidate;
use App\Form\CandidateType;
use App\Repository\CandidateRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/candidate")
 */
class CandidateController extends AbstractController
{
    /**
     * @Route("/", name="candidate_index", methods={"GET"})
     */
    public function index(CandidateRepository $candidateRepository): Response
    {
        return $this->render('candidate/index.html.twig', [
            'candidates' => $candidateRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="candidate_new")
     */
    public function new(Request $request): Response
    {
        $candidate = new Candidate();
        $form = $this->createForm(CandidateType::class, $candidate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($candidate);
            $entityManager->flush();

            return $this->redirectToRoute('candidate_index');
        }

        return $this->render('candidate/new.html.twig', [
            'candidate' => $candidate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="candidate_show", methods={"GET"})
     */
    public function show(Candidate $candidate): Response
    {
        return $this->render('candidate/show.html.twig', [
            'candidate' => $candidate,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="candidate_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Candidate $candidate): Response
    {
        $form = $this->createForm(CandidateType::class, $candidate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('candidate_index', [
                'id' => $candidate->getId(),
            ]);
        }

        return $this->render('candidate/edit.html.twig', [
            'candidate' => $candidate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="candidate_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Candidate $candidate): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidate->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($candidate);
            $entityManager->flush();
        }

        return $this->redirectToRoute('candidate_index');
    }
}

templates/candidate/_delete_form.html.twig
<form method="post" action="{{ path('candidate_delete', {'id': candidate.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidate.id) }}">
    <button class="btn">Delete</button>
</form>

templates/candidate/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/candidate/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Candidate{% endblock %}

{% block body %}
    <h1>Edit Candidate</h1>

    {{ include('candidate/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('candidate_index') }}">back to list</a>

    {{ include('candidate/_delete_form.html.twig') }}
{% endblock %}

templates/candidate/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidate index{% endblock %}

{% block body %}
    <h1>Candidate index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_de_naissance</th>
                <th>Email</th>
                <th>Date_candidature</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
            <tr>
                <td>{{ candidate.id }}</td>
                <td>{{ candidate.Nom }}</td>
                <td>{{ candidate.Prenom }}</td>
                <td>{{ candidate.dateDeNaissance ? candidate.dateDeNaissance|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ candidate.email }}</td>
                <td>{{ candidate.dateCandidature ? candidate.dateCandidature|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('candidate_show', {'id': candidate.id}) }}">show</a>
                    <a href="{{ path('candidate_edit', {'id': candidate.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('candidate_new') }}">Create new</a>
{% endblock %}

templates/candidate/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Candidate{% endblock %}

{% block body %}
    <h1>Create new Candidate</h1>

    {{ include('candidate/_form.html.twig') }}

    <a href="{{ path('candidate_index') }}">back to list</a>
{% endblock %}

templates/candidate/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidate{% endblock %}

{% block body %}
    <h1>Candidate</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ candidate.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ candidate.Nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ candidate.Prenom }}</td>
            </tr>
            <tr>
                <th>Date_de_naissance</th>
                <td>{{ candidate.dateDeNaissance ? candidate.dateDeNaissance|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ candidate.email }}</td>
            </tr>
            <tr>
                <th>Date_candidature</th>
                <td>{{ candidate.dateCandidature ? candidate.dateCandidature|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('candidate_index') }}">back to list</a>

    <a href="{{ path('candidate_edit', {'id': candidate.id}) }}">edit</a>

    {{ include('candidate/_delete_form.html.twig') }}
{% endblock %}